version: 1.0.{build}
image:
- Visual Studio 2017
install:
- choco install opencover.portable
- choco install codecov
configuration:
- Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: dotnet restore .\src\Database.Versioning.sln
build_script:
- ps: dotnet build .\src\Database.Versioning.sln --configuration $env:CONFIGURATION --no-restore
after_build:
- ps: dotnet pack .\src\Database.Versioning.sln --configuration $env:CONFIGURATION /p:PackageVersion={version}
- ps: dotnet publish .\src\Database.Versioning.sln --configuration $env:CONFIGURATION --no-restore --no-build /p:DebugType=Full
test_script: 
- ps: dotnet test .\src\Tests\Database.Versioning.Tests\ --configuration $env:CONFIGURATION --no-restore --no-build --logger:trx
after_test:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --configuration $env:CONFIGURATION --no-restore --no-build --logger:trx" -filter:"+[*]* -[*.Tests*]*" -oldStyle -output:"TestCoverage.xml"
- ps: . "C:\ProgramData\chocolatey\lib\codecov\tools\codecov.exe" -f "TestCoverage.xml"
- ps: >-
    Write-Host "Uploading test results"

    $uploadPath = "https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)"

    $testResults = Resolve-Path .\src\Tests\*.Tests\TestResults\*.trx

    Write-Host "Sending $testResults to $uploadPath"

    $wc = New-Object 'System.Net.WebClient'

    Foreach ($testResult in $testResults)
    {
        $wc.UploadFile($uploadPath, $testResult)
    }
artifacts:
- path: src\Database.Versioning\bin\%configuration%
  name: Database.Versioning
